app/article/article_blueprint.py
from app import db
from flask import Blueprint, render_template, request, redirect, url_for
from flask_security import login_required
from models import Articles, Users
from .article_forms import ArticleForm
from lib.StandsMenu import StandsMenu


article = Blueprint('article', __name__, template_folder='templates')


@article.route('/create_article', methods=['POST', 'GET'])
@login_required
def create_article():
    standsMenu = StandsMenu.standslist
    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']

        try:
            article = Articles(title=title, content=content)
            db.session.add(article)
            db.session.commit()
        except:
            print('Something wrong')
        return redirect(url_for('index_page'))

    form = ArticleForm()
    return render_template(
        'create_or_update_article.html',
        title=True,
        standsMenu=standsMenu,
        create=True,
        form=form,
        author='Иван Иванович'
    )


@article.route('/<slug>/edit_article', methods=['POST', 'GET'])
@login_required
def edit_article(slug):
    standsMenu = StandsMenu.standslist
    article = Articles.query.filter(Articles.slug == slug).first_or_404()

    if request.method == 'POST':
        form = ArticleForm(formdata=request.form, obj=article)
        form.populate_obj(article)
        db.session.commit()

        return redirect(url_for('article.article_index', slug=article.slug))

    form = ArticleForm(obj=article)
    return render_template(
        'create_or_update_article.html',
        title=True,
        standsMenu=standsMenu,
        update=True,
        slug=article.slug,
        form=form
    )


@article.route('/<slug>')
def article_index(slug):
    standsMenu = StandsMenu.standslist
    article = Articles.query.filter(Articles.slug == slug).first_or_404()
    if article.user_id_fk:
        user = Users.query.filter(Users.id == article.user_id_fk).first()
        user = user.fullname
    else:
        user = ''

    return render_template(
        'article/index.html',
        title=True,
        standsMenu=standsMenu,
        article=article,
        author=user,
        slug=slug,
        date='05.09.78',
        time='12:42'
    )

app/stands/stands_blueprint.py
from app import db
from flask import Blueprint, render_template, request, redirect, url_for
from flask_security import login_required
from models import Stands, Users
from .stands_forms import StandsForm
from lib.ListPrepare import ListPrepare
from lib.StandsMenu import StandsMenu


stands = Blueprint('museumstands', __name__, template_folder='templates')


@stands.route('/create_stand', methods=['POST', 'GET'])
@login_required
def create_stand():
    standsMenu = StandsMenu.standslist
    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']

        try:
            stand = Stands(title=title, content=content)
            db.session.add(stand)
            db.session.commit()
        except:
            print('Something wrong')
        return redirect(url_for('museumstands.stands_index'))

    form = StandsForm()
    return render_template(
        'create_or_update_stand.html',
        title=True,
        standsMenu=standsMenu,
        create=True,
        form=form,
        author='Иван Иванович'
    )


@stands.route('/<slug>/edit_stand', methods=['POST', 'GET'])
@login_required
def edit_stand(slug):
    standsMenu = StandsMenu.standslist
    stands = Stands.query.filter(Stands.slug == slug).first_or_404()

    if request.method == 'POST':
        form = StandsForm(formdata=request.form, obj=stands)
        form.populate_obj(stands)
        db.session.commit()

        return redirect(url_for('museumstands.stand_page', slug=stands.slug))

    form = StandsForm(obj=stands)
    return render_template(
        'create_or_update_stand.html',
        title=True,
        standsMenu=standsMenu,
        update=True,
        slug=stands.slug,
        form=form
    )


@stands.route('/')
def stands_index():
    standsMenu = StandsMenu.standslist
    stands_list = Stands.query.order_by(Stands.stand_id)

    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    paginate = stands_list.paginate(page=page, per_page=6)
    stands = ListPrepare(paginate.items, 'stand_id')
    stands = stands.get_list()
    return render_template(
        'stands/index.html',
        activeButtonState=2,
        title=True,
        standsMenu=standsMenu,
        pageName='Стенды музея',
        stands=stands,
        paginate=paginate
    )


@stands.route('/<slug>')
def stand_page(slug):
    standsMenu = StandsMenu.standslist
    stand = Stands.query.filter(Stands.slug == slug).first_or_404()
    if stand.user_id_fk:
        user = Users.query.filter(Users.id == stand.user_id_fk).first()
        user = user.fullname
    else:
        user = ''

    return render_template(
        'stand.html',
        activeButtonState=2,
        title=True,
        standsMenu=standsMenu,
        stand=stand,
        author=user,
        slug=slug
    )

app/templates/includes/footer.html
<footer class="footer con-shadow">
    <div class="container py-4">
        <div class="row">
            <div class="col-md-3 footer-logo">
                <img src="{{ url_for('static', filename='images/svg/logo.svg') }}" width="160" height="70" alt="">
            </div>
            <div class="col-md-3 footer-item">
                <h4>Меню</h4>
                <div class="small">
                    <ul>
                        <li class="footer-link"><a href="{{ url_for('index_page') }}">Главная</a></li>
                        <li class="footer-link"><a href="{{ url_for('museumstands.stands_index') }}">Стенды</a></li>
                        <li class="footer-link"><a href="{{ url_for('about_page') }}">О музее</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md-3">
                <h4>Информация</h4>
                <div class="small">
                    Этот сайт (дизайн и приложение) является диплопным проектом, разработанным студентом группы ИП-41 Рублев Глеб</p>
                </div>
                <!-- Разработал xenongee -->
                <!-- Ссылки на меня: -->
                <!-- https://xnngee.github.io/ -->
                <!-- https://vk.com/xenongee -->
                <p class="mb-0 mt-2 small mono abberation-shadow">
                    <a class="text-decoration-none" href="https://xnngee.github.io/" target="_blank">designed by <img class="xglogo" alt="xenongee" title="xenongee" src="{{ url_for('static', filename='images/xg_logos/xg-logo.png') }}"></a>
                </p>
            </div>
            <div class="col-md-3">
                <h4>Контакты</h4>
                <div class="small">
                    <p>610005 г. Киров, Октябрьский проспект, д.97 <br>Руководитель музея В. А. Садовников.</p>
                </div>
            </div>
        </div>
        <hr class="footer-hr my-4">
        <div class="row">
            <div class="col-md-12 small">КОГПОБУ "Кировский авиационный техникум"<br>Copyright © 2020</div>
        </div>
    </div>
</footer>

app/templates/includes/head.html
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>
  {% if pageName and title %}
  {{ pageName }} - Музей профессионального образования
  {% else %}
  Музей профессионального образования
  {% endif %}
</title>
<meta name="description" content="Музей профессионального образования КОГПОБУ Кировский авиационный техникум">
<meta name="keywords"
content="Музей КАТ, Музей Кировского авиационного техникума, Музей профессионального образования, Музей Киров, Музей, КАТ, КОГПОБУ, Кировский авиационный техникум, Киров КАТ">
<!-- favicon -->
<link rel="apple-touch-icon" sizes="57x57" href="{{ url_for('static', filename='images/favicons/apple-icon-57x57.png') }}">
<link rel="apple-touch-icon" sizes="60x60" href="{{ url_for('static', filename='images/favicons/apple-icon-60x60.png') }}">
<link rel="apple-touch-icon" sizes="72x72" href="{{ url_for('static', filename='images/favicons/apple-icon-72x72.png') }}">
<link rel="apple-touch-icon" sizes="76x76" href="{{ url_for('static', filename='images/favicons/apple-icon-76x76.png') }}">
<link rel="apple-touch-icon" sizes="114x114" href="{{ url_for('static', filename='images/favicons/apple-icon-114x114.png') }}">
<link rel="apple-touch-icon" sizes="120x120" href="{{ url_for('static', filename='images/favicons/apple-icon-120x120.png') }}">
<link rel="apple-touch-icon" sizes="144x144" href="{{ url_for('static', filename='images/favicons/apple-icon-144x144.png') }}">
<link rel="apple-touch-icon" sizes="152x152" href="{{ url_for('static', filename='images/favicons/apple-icon-152x152.png') }}">
<link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='images/favicons/apple-icon-180x180.png') }}">
<link rel="icon" type="image/png" sizes="192x192" href="{{ url_for('static', filename='images/favicons/android-icon-192x192.png') }}">
<link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='images/favicons/favicon-32x32.png') }}">
<link rel="icon" type="image/png" sizes="96x96" href="{{ url_for('static', filename='images/favicons/favicon-96x96.png') }}">
<link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='images/favicons/favicon-16x16.png') }}">
<link rel="manifest" href="{{ url_for('static', filename='images/favicons/manifest.json') }}">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="{{ url_for('static', filename='images/favicons/ms-icon-144x144.png') }}">
<meta name="theme-color" content="#ffffff">
<!-- frameworks -->
<link rel="stylesheet" href="{{ url_for('static', filename='frameworks/bootstrap/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='frameworks/smartphoto/smartphoto.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='frameworks/fontawesome/css/all.min.css') }}">
<!-- custom style -->
<link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
{% if jumbotron_img_url %}
  <style>
    .jumbotron-bg {
      background: linear-gradient(0deg, rgb(255, 255, 255) 20%, rgba(255, 255, 255, 0.33) 70%),
                  url('{{ url_for('static', filename=jumbotron_img_url) }}') no-repeat center center;
      background-size: cover;
    }
  </style>
{% else %}
  <style>
    .jumbotron-bg {
      background: linear-gradient(0deg, rgb(255, 255, 255) 20%, rgba(255, 255, 255, 0.33) 70%),
        url('{{ url_for('static', filename='images/placeholders/placeholder_700x500.jpg') }}') no-repeat center center;
      background-size: cover;
    }
  </style>
{% endif %}

app/templates/includes/header.html
{% if current_user.has_role('admin') %}
    {% set roleName = 'Администратор' %}
{% elif current_user.has_role('redactor')%}
    {% set roleName = 'Редактор' %}
{% endif %}

<header>
  {% if current_user.has_role('admin') or current_user.has_role('redactor') %}
  <div class="fixed-top navbar-notification">
    <div class="container">
      <div class="row align-items-center text-white">
        <div class="col-auto justify-content-start marq1uee" data-direction="right" data-duplicated="true">Вы зашли за
          {{ roleName | lower }}а</div>
        <div class="col-auto flex-grow-1 "><a href="/adminpanel">Войти в
            панель</a></div>
        {# data-toggle="modal" data-target="#LoginModalCenter" #}
        <div class="col-auto d-flex justify-content-end"><a href="/logout">Выйти</a></div>
      </div>
    </div>
  </div>
  {% endif %}
  <nav class="navbar navbar-default navbar-expand-md fixed-top navbar-light bg-white con-shadow">
    <div class="container">
      <a class="navbar-brand" href="{{ url_for('index_page') }}">
        <img src="{{ url_for('static', filename='images/svg/logo.svg') }}"
          alt="Музей профессионального образования КАТ">
      </a>
      <button class="navbar-toggler" id="navbarToggler" type="button" data-toggle="collapse"
        data-target="#navbarButtons" aria-controls="navbarButtons" aria-expanded="false" aria-label="Открыть меню">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="navbar-collapse collapse" id="navbarButtons">
        <ul class="nav navbar-nav ml-auto">
          <li class="nav-item {% if activeButtonState == 1 %}active{% endif %}">
            <a class="nav-link" href="{{ url_for('index_page') }}">Главная</a>
          </li>
          <li class="nav-item dropdown {% if activeButtonState == 2 %}active{% endif %}">
            <a class="nav-link dropdown-toggle nav-stend dropdown-pc" href="{{ url_for('museumstands.stands_index') }}">
              Стенды
            </a>
            <a class="nav-link dropdown-toggle nav-stend dropdown-mobile" href="{{ url_for('museumstands.stands_index') }}" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              Стенды
            </a>
            <div class="dropdown-menu dropdown-menu-nav dropdown-menu-right" aria-labelledby="navbarDropdown">
              {% for i in range(standsMenu|length) if not i >= 8 %}
                    <a class="dropdown-item" href="{{ url_for('museumstands.stand_page', slug=standsMenu[i].slug) }}">{{ standsMenu[i].title }}</a>
              {% endfor %}
              <a class="dropdown-item dropdown-mobile" href="{{ url_for('museumstands.stands_index') }}">Открыть раздел "Стенды"</a>
              
            </div>
          </li>
          <li class="nav-item {% if activeButtonState == 3 %}active{% endif %}">
            <a class="nav-link" href="{{ url_for('about_page') }}">О музее</a>
          </li>
          <li class="nav-item dropdown {% if activeButtonState == 4 %}active{% endif %}">
            <a class="nav-link dropdown-toggle nav-stend dropdown" href="" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-info-circle"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-nav dropdown-menu-right" aria-labelledby="navbarDropdown">
              <span class="dropdown-header">Поиск по сайту</i></span>
              <form class="input-group p-3" action="/search" method="get">
                <input class="form-control" id="searchForm" type="text" autocomplete="off" placeholder="Поиск..." name="q" value="{{ request.args.get('q', '') }}">
                <div class="input-group-append">
                  <button class="btn btn-outline-primary" type="submit"><i class="fas fa-search pr-2"></i>Найти</button>
                </div>
              </form>            
              {% if current_user.has_role('admin') or current_user.has_role('redactor') %}  
                <div class="dropdown-divider"></div>
                <span class="dropdown-header">Создание новых страниц</span>
                <div class="btn-group" role="group" aria-label="articleCreateButtons">
                  <a class="btn btn-primary btn-sm" href="{{ url_for('article.create_article') }}" role="button">Новая статья</a>
                  <a class="btn btn-primary btn-sm" href="{{ url_for('museumstands.create_stand') }}" role="button">Новый стeнд</a>
                </div>
              {% else %}
                <div class="dropdown-divider"></div>
                <span class="dropdown-header">Вход для сотрудников музея</span>
                <a class="dropdown-item" href="/login"><i class="fas fa-sign-in-alt pr-2"></i>Авторизоваться</a>
                <!-- <a class="dropdown-item" href="#" data-toggle="modal" data-target="#LoginModalCenter"><i class="fas fa-sign-in-alt pr-2"></i>Авторизоваться</a> -->
              {% endif %}
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/templates/includes/jumbotron.html
<section class="jumbotron-section">
    <div class="jumbotronBg-overlay">
        <div class="jumbotron-bg"></div>
    </div>
    <div class="jumbotron cover d-flex align-items-end">
        <div class="container text-black">
            {% if pageName %}
            <h1 class="display-4 brickword">{{ pageName }}</h1>
            {% endif %}
            {#<p>{% if time %}{{ time }}, {% endif %}{% if date %}{{ date }} - {% endif %}{% if author %}Автор:
                {{ author }}{% endif %}</p>#}
            {% if article and (current_user.has_role('admin') or current_user.has_role('redactor')) %}
                <a class="btn btn-primary btn-sm" href="{{ url_for('article.edit_article', slug=slug) }}"><i class="fas fa-edit pr-2"></i>Изменить страницу</a>
            {% elif stand and (current_user.has_role('admin') or current_user.has_role('redactor')) %}
                <a class="btn btn-primary btn-sm" href="{{ url_for('museumstands.edit_stand', slug=slug) }}"><i class="fas fa-edit pr-2"></i>Изменить стенд</a>
            {% endif %}
        </div>
    </div>
</section>

app/templates/includes/modal.html
<div class="modal fade" id="LoginModalCenter" tabindex="-1" role="dialog" aria-labelledby="LoginModalCenterTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Авторизация</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="my-1 mr-sm-2">
                        <label class="control-label m-0">Войдите, чтобы продолжить</label>
                    </div>
                    <div class="my-1 mr-sm-2">
                        <label class="control-label m-0">Были введены неверные данные</label>
                    </div>
                    <div class="form-group pt-3">
                        <input type="login" class="form-control" placeholder="Логин" aria-label="">
                    </div>
                    <div class="input-group pb-3">
                        <input type="password" class="form-control" placeholder="Пароль" aria-label="">
                        <div class="input-group-append">
                            <button class="btn btn-outline-primary" type="button"><i
                                    class="fas fa-eye-slash"></i></button>
                        </div>
                    </div>
                    <div class="custom-control custom-checkbox my-1 mr-sm-2">
                        <input type="checkbox" class="custom-control-input" id="rememberSession">
                        <label class="custom-control-label" for="rememberSession">Запомнить</label>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary mr-auto">Войти</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="imageLoaderModalCenter" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Выбрать изображение</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <span class="input-text">Загрузить изображения:</span>                
                <div class="custom-file mt-3" data-toggle="tooltip" data-placement="bottom" data-html="true"
                    title="Нажмите сюда, чтобы выбрать фоновое изображение из вашего компьюетра. <u>Данное изображение сохранится на сервере</u>, после чего вы можете их повторно использовать нажав на кнопку <b>Выбрать на сервере</b>">
                    <input type="file" class="custom-file-input" id="inputGroupFile">
                    <label class="custom-file-label" for="inputGroupFile">Выбрать из комьютера</label>
                </div>
                <button class="btn btn-secondary  mt-3" type="button" data-toggle="tooltip" data-placement="bottom"
                    title="Нажмите, если вы хотите выбрать фоновое изображение, которое было загружено на сервере ранее">Выбрать
                    на сервере</button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Закрыть</button>
            </div>
        </div>
    </div>
</div>

app/templates/includes/preloader.html
<div class="preloader preloader-enable d-flex flex-column justify-content-center">
    <div class="loader text-center">Сайт загружается. Пожалуйста, подождите<span></span></div>
</div>

app/templates/includes/scripts.html
<!-- frameworks -->
<script src="{{ url_for('static', filename='frameworks/jquery/jquery-3.4.1.slim.js') }}"></script>
<script src="{{ url_for('static', filename='frameworks/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='frameworks/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ url_for('static', filename='frameworks/smartphoto/smartphoto.min.js') }}"></script>

<!-- assets -->
<script src="{{ url_for('static', filename='js/preloader.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/dropdown_hover.jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/jumbotron-parallax.jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/tilt.jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/mousewheel.jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/main.js') }}"></script>

<script>
    $("[data-tilt]").tilt({
        maxTilt: 2
    })
    $(document).ready((function () {
        new SmartPhoto(".sphoto")
        $(".smartphoto-nav ul").mousewheel((function (s, o) {
            this.scrollLeft -= 90 * o, s.preventDefault()
        }))
    }))
</script>

{% if creatingContent == True %}
<script type="text/javascript" src="{{ url_for('static', filename='frameworks/tinymce/tinymce.min.js') }}"></script>
<script type="text/javascript">
    tinymce.init({
        selector: '#content',
        language: 'ru',
        skin: 'CUSTOM',
        min_height: 700,
        plugins: [
            'advlist autolink link image imagetools lists charmap print preview hr anchor pagebreak spellchecker',
            'searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking',
            'save table contextmenu directionality template paste textcolor codesample'
        ],
        menu: {
            file: {
                title: 'File',
                items: 'newdocument restoredraft | preview | print '
            },
            edit: {
                title: 'Edit',
                items: 'undo redo | cut copy paste | selectall | searchreplace'
            },
            view: {
                title: 'View',
                items: 'code | visualaid visualchars visualblocks | preview fullscreen'
            },
            insert: {
                title: 'Insert',
                items: 'image link media template codesample inserttable | charmap emoticons hr | pagebreak nonbreaking anchor toc | insertdatetime'
            },
            format: {
                title: 'Format',
                items: 'bold italic underline strikethrough superscript subscript codeformat | formats blockformats fontformats fontsizes align | forecolor backcolor | removeformat'
            },
            tools: {
                title: 'Tools',
                items: 'code wordcount'
            },
            table: {
                title: 'Table',
                items: 'inserttable | cell row column | tableprops deletetable'
            }
        },
        imagetools_toolbar: "rotateleft rotateright | flipv fliph | editimage imageoptions",
        toolbar: 'undo redo | fontsizeselect | bold italic underline strikethrough | forecolor backcolor removeformat | bullist numlist | outdent indent | alignleft aligncenter alignright alignjustify | styleselect | paste copy cut selectall | table | pagebreak | link template image media | code visualblocks preview',
        toolbar_mode: 'sliding',
        contextmenu: "cut copy paste | selectall | inserttable | cell row column | tableprops deletetable | link",
        // images_upload_url: {# {{ url_for('post.imageuploader') }} #}'',
        automatic_uploads: true,
        images_reuse_filename: false,
        images_upload_base_path: '/static/uploads',
        codesample_languages: [{
                text: 'HTML/XML',
                value: 'markup'
            },
            {
                text: 'JavaScript',
                value: 'javascript'
            },
            {
                text: 'CSS',
                value: 'css'
            },
            {
                text: 'Processing',
                value: 'processing'
            },
            {
                text: 'Python',
                value: 'python'
            }
        ],
        width: "100%",
        templates: [{
            title: 'Изображение',
            description: '',
            content: '<div class="container"><a class="sphoto" href="http://lorempixel.com/800/600/" data-caption="Изображение" data-id="image_article" data-group="article"><img class="sectionImage" style="display: block; margin-left: auto; margin-right: auto;" src="http://lorempixel.com/800/600/" alt=""></a></div>'
        }],
        setup: function (editor) {
            editor.on('keydown', function () {
                checkForm()
            });
        }
    });
</script>
<script type="text/javascript" src="{{ url_for('static', filename='js/checkForm.min.js') }}"></script>
{% endif %}